# Generated by Django 4.1.6 on 2023-08-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contesthome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_img1', models.ImageField(upload_to='contest')),
                ('s_img2', models.ImageField(upload_to='contest')),
                ('s_img3', models.ImageField(upload_to='contest')),
                ('con_name', models.CharField(max_length=120)),
                ('con_des', models.CharField(max_length=500)),
                ('entry_fees', models.IntegerField()),
                ('winng_prize', models.IntegerField()),
                ('start_con', models.DateField(max_length=30)),
                ('end_con', models.DateField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Contestoverviwes',
        ),
    ]
