# Generated by Django 4.1.6 on 2023-08-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_contesthome_delete_contestoverviwes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesthome',
            name='con_des',
            field=models.TextField(max_length=500),
        ),
    ]
